//selectiong elements
let button = document.querySelector("button");
let m1 = document.querySelector("#m1");
let m2 = document.querySelector("#m2");
let img1 = document.querySelector("#img1");
let img2 = document.querySelector("#img2");
let sp1 = document.querySelector("#sp1");
let sp2 = document.querySelector("#sp2");
let container = document.querySelector("#container");

//Declaring variables
let marks1 = 0;
let marks2 = 0;
let chance = 0;

//getting user's names as input
let player1 = prompt("Enter player1's name");
let player2 = prompt("Enter player2's name");

//changing names of player1 and player2
sp1.innerHTML = player1;
sp2.innerHTML = player2;

//ading EventListener to button "ROLL"
button.addEventListener("click", () => {
    // function myTimer() {

    //     img1.src = `dice_${Math.floor(Math.random() * 6) + 1}.png`;
    // }
    // setInterval(myTimer, 200);

    //generating random numbers as dice values
    let rand1 = Math.floor(Math.random() * 6) + 1
    let rand2 = Math.floor(Math.random() * 6) + 1

    //change image corresponding to the dice value
    img1.src = `dice_${rand1}.png`
    img2.src = `dice_${rand2}.png`

    //a variable called chance to switch the roll function between the two users 
    //if chance =0 -->player1___if chance =1-->player2
    if (chance === 0) {
        //marks1 store the value generated by the two dices of the first player
        marks1 += (rand1 + rand2);
        //chance value is changed to give the other player a chance
        chance += 1;
        //check whether both values are 1
        //if true make marks1=0
        if (rand1 === 1 && rand2 === 1) {
            marks1 = 0;
           
        }
        //check whether both values are same (not 1s)
        //change chance value back to give the same player the next chance
        else if (rand1 === rand2) {
            chance -= 1;
        }
        //if marks is going to exceed 100 keep marks the same value as it is
        if (marks1 > 100) {
            marks1 = marks1 - (rand1 + rand2);

        }
        //change the innerHTML of the span contaning marks to 
        m1.innerHTML = marks1
        //changing styles of elements after reaching 100
        if (marks1 === 100) {
            button.disabled = true;
            button.style.background = "rgb(255, 139, 143)";
            button.style.color = "white";
            sp1.innerHTML = "Winner"
            sp1.style.color = "white";
            sp1.style.background = "#e81766"

            m1.style.background = "#ffea00";
            sp2.innerHTML = "";
            sp2.style.background = "none";
            container.style.background= "url(bg1.jpg)"
        }
    }
    else {
        marks2 += (rand1 + rand2);
        chance -= 1;

        if (rand1 === 1 && rand2 === 1) {
            marks2 = 0;
           
        }
        else if (rand1 === rand2) {
            chance += 1;
        }
        if (marks2 > 100) {

            marks2 = marks2 - (rand1 + rand2);
        }
        m2.innerHTML = marks2
        if (marks2 === 100) {
            button.disabled = true;
            button.style.background = "rgb(255, 139, 143)";
            button.style.color = "white";
            sp2.innerHTML = "Winner"
            sp2.style.color = "white";
            sp2.style.background = "#e81766"

            m2.style.background = "#ffea00";
            sp1.innerHTML = "";
            sp1.style.background = "none";
            container.style.backgroundImage = "url(bg1.jpg)"
        }
    }
    console.log(rand1, rand2)

})